In [123]:
import numpy as np

In [217]:
class HopfieldNetwork:
    def __init__(self, n):
        self.n = n
        self.weights = []
        self.threshold = 0
    
    def fit(self, X):
        self.weights = np.zeros((self.n, self.n))
        for x in X:
            self.weights += np.outer(x, x)
            print(self.weights)
        # self.weights /= self.n
        np.fill_diagonal(self.weights, 0)
        self.threshold = 0
    
    def predict(self, x):
        y = np.dot(self.weights, x) - self.threshold
        y[y >= 0] = 1
        y[y < 0] = -1
        return y

In [219]:
from random import randint
X = np.array([[1, -1, 1, -1, 1, 1, -1, 1],
              [1, 1, 1, -1, -1, -1, 1, 1]])
hn = HopfieldNetwork(8)
hn.fit(X)
pred = hn.predict([1, -1, 1, 0, 1, 1, -1, 0])
print(f'predicted pattern: {pred}')

[[ 1. -1.  1. -1.  1.  1. -1.  1.]
 [-1.  1. -1.  1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.]
 [-1.  1. -1.  1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.]
 [-1.  1. -1.  1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.]]
[[ 2.  0.  2. -2.  0.  0.  0.  2.]
 [ 0.  2.  0.  0. -2. -2.  2.  0.]
 [ 2.  0.  2. -2.  0.  0.  0.  2.]
 [-2.  0. -2.  2.  0.  0.  0. -2.]
 [ 0. -2.  0.  0.  2.  2. -2.  0.]
 [ 0. -2.  0.  0.  2.  2. -2.  0.]
 [ 0.  2.  0.  0. -2. -2.  2.  0.]
 [ 2.  0.  2. -2.  0.  0.  0.  2.]]
predicted pattern: [ 1. -1.  1. -1.  1.  1. -1.  1.]
