In [48]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

In [13]:
weights = np.random.rand(2, 4)
print(weights)
input_vector = np.array([1, 2, 3, 4])
print(weights - input_vector)

[[0.88475437 0.03569306 0.19177026 0.71159836]
 [0.11446575 0.40721758 0.93947545 0.11096284]]
[[-0.11524563 -1.96430694 -2.80822974 -3.28840164]
 [-0.88553425 -1.59278242 -2.06052455 -3.88903716]]


In [54]:
class KSOFM:
    def __init__(self, num_input, num_output, learning_rate=0.1, epochs=100):
        self.num_input = num_input
        self.num_output = num_output
        self.learning_rate = learning_rate
        self.weights = np.random.rand(num_output, num_input)
        # self.weights = np.array([
        #     [0.3, 0.5, 0.7, 0.2],
        #     [0.6, 0.7, 0.4, 0.3]
        # ])
        self.epochs = epochs
    
    def train(self, X):
        for i in range(self.epochs):
            for _, x in enumerate(X):
                # print(x)
                # print(self.weights)
                # Calculate the distance between the input vector and each weight vector
                distances = np.linalg.norm(self.weights - x, axis=1)
                # print(distances)
                # Find the index of the winning neuron
                winner = np.argmin(distances)
                # Update the weights of the winning neuron
                self.weights[winner] += self.learning_rate * (x - self.weights[winner])
                # print(f'Epoch {i+1}, Input {x}, Winner {winner}, Weights {self.weights}')
            print(f'Epoch {i+1}, Weights {self.weights}')
        return self.weights
    
    def predict(self, X):
        y_pred = []
        for _, x in enumerate(X):
            distances = np.linalg.norm(self.weights - x, axis=1)
            winner = np.argmin(distances)
            y_pred.append(winner)
        return y_pred

In [47]:
X = np.array([[1, 0, 1, 0], [1, 0, 0, 0], [1, 1, 1, 1], [0, 1, 1, 0]])
ksofm = KSOFM(4, 2, learning_rate=0.6, epochs=10)
w = ksofm.train(X)
# print(w)

Epoch 1, Weights [[0.97878381 0.3230868  0.07084944 0.11624144]
 [0.36210164 0.87012074 0.99282533 0.27186574]]
Epoch 2, Weights [[0.99660541 0.05169389 0.25133591 0.01859863]
 [0.29793626 0.97921932 0.99885205 0.28349852]]
Epoch 3, Weights [[0.99945687 0.00827102 0.28021375 0.00297578]
 [0.2876698  0.99667509 0.99981633 0.28535976]]
Epoch 4, Weights [[9.99913098e-01 1.32336355e-03 2.84834199e-01 4.76124927e-04]
 [2.86027168e-01 9.99468015e-01 9.99970613e-01 2.85657562e-01]]
Epoch 5, Weights [[9.99986096e-01 2.11738168e-04 2.85573472e-01 7.61799883e-05]
 [2.85764347e-01 9.99914882e-01 9.99995298e-01 2.85705210e-01]]
Epoch 6, Weights [[9.99997775e-01 3.38781069e-05 2.85691756e-01 1.21887981e-05]
 [2.85722296e-01 9.99986381e-01 9.99999248e-01 2.85712834e-01]]
Epoch 7, Weights [[9.99999644e-01 5.42049710e-06 2.85710681e-01 1.95020770e-06]
 [2.85715567e-01 9.99997821e-01 9.99999880e-01 2.85714053e-01]]
Epoch 8, Weights [[9.99999943e-01 8.67279536e-07 2.85713709e-01 3.12033232e-07]
 [2.8571

In [52]:
df = pd.read_csv('breast-cancer-wisconsin-data_data.csv')
df['diagnosis'].replace('M', 1, inplace=True)
df['diagnosis'].replace('B', 0, inplace=True)

X = df.iloc[:, 2:32]
y = df.iloc[:, 1]
X = np.array(X)
y = np.array(y)
    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [63]:
ksofm = KSOFM(30, 2, learning_rate=0.1, epochs=3000)
w = ksofm.train(X_train)
pred = ksofm.predict(X_test)
print(pred)
print(y_test)
acc = accuracy_score(y_test, pred)
print(acc)

Epoch 1, Weights [[1.97424443e+01 2.38172527e+01 1.30625652e+02 1.22233535e+03
  1.00655905e-01 1.49343087e-01 1.87657607e-01 1.02452892e-01
  1.86670517e-01 5.93679195e-02 7.44200282e-01 1.33776671e+00
  5.20829038e+00 9.40993952e+01 6.70133104e-03 3.29038889e-02
  4.15725863e-02 1.54817114e-02 1.85125039e-02 3.73124304e-03
  2.46306689e+01 3.18890892e+01 1.64076259e+02 1.86514921e+03
  1.39890725e-01 3.92020970e-01 4.69899996e-01 1.95742272e-01
  3.05413523e-01 8.53766879e-02]
 [1.29635993e+01 1.78615236e+01 8.36057241e+01 5.30868585e+02
  9.58136383e-02 8.53015072e-02 5.95321076e-02 3.50509496e-02
  1.70531181e-01 6.18953806e-02 3.20709840e-01 9.63643671e-01
  2.19644370e+00 2.64898391e+01 6.95209800e-03 1.95782953e-02
  2.59895859e-02 1.01390978e-02 1.95363494e-02 3.14102262e-03
  1.46650042e+01 2.26777851e+01 9.55303109e+01 6.82582736e+02
  1.30401581e-01 2.03772608e-01 2.13465865e-01 9.06972340e-02
  2.81232910e-01 7.96632985e-02]]
Epoch 2, Weights [[1.97429982e+01 2.38178672e+01